name: 'deploy-infra'

 

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - templates/*
      
permissions:
  id-token: write
  contents: read
jobs:
  terraform: 
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.4

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set environment variables for Azure authentication
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Terraform Init
        run: terraform -chdir="templates" init -input=false -backend-config="config/prd.tfbackend" -backend-config="key=infra.tfstate"
        

      - name: Terraform Plan
        run: terraform -chdir="templates" plan -input=false -var-file="config/prd.tfbackend" -var-file="environments/prd.tfvars" -out=tfplan

      #- name: Terraform Apply
      #  run: terraform apply -input=false -auto-approve tfplan