name: 'deploy-infra'

on:
  push:
    branches:
      - master
    paths: 
      - _deployment/terraform/common/*
      - .github/workflows/deploy-common.yml

jobs:
  terraform: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Terraform Init
        run: terraform init -input=false -backend-config=_deployment/terraform/common/backend.tfvars

      - name: Terraform Plan
        run: terraform --chdir="/" plan -input=false -var-file=_deployment/terraform/common/terraform.tfvars -out=tfplan

      #- name: Terraform Apply
      #  run: terraform apply -input=false -auto-approve tfplan